### ISSUE TITLE
Grants table - does not match

### ISSUE THREAD

**Issue by ghost** [INDIGO-Initiative/indigo-data-standard#23]
The existing table does not match data definitions documentation at all

**Comment by ghost** [comment]
Call with @Juliana211 

We think there is no data here - double check that. 

If not, then just remove this tab for now - it's not being used, we are not sure of use, and at the point we do want to use we will re-review then.

**Comment by ghost** [comment]
There is no data in the grants table - I will remove it

**Comment by Juliana211** [comment]
ok!

**Comment by ghost** [comment]
Done
