### ISSUE TITLE
Project, "Maximum potential outcome payment" needs extra definition

### ISSUE THREAD

**Issue by ghost** [INDIGO-Initiative/indigo-data-standard#26]
**Amount**

Firstly, it needs it's own amount and amount_USD  columns. We can assume the current values are in local currency and move them to the amount column, moving the amount_USD entry blank.

**Currency**

But then we have to do something about currency. There are 2 options:

_Option A_

Add a Currency field clearly to the top of the "Overall project finance" section.
Remove the currency field from "Total investment commitment" and "Total outcome payments made".

Choose this option if all three fields should always be in the same currency.

_Option B_

Add a Currency field to  "Maximum potential outcome payment".

Choose this option if it's possible that   "Maximum potential outcome payment", "Total investment commitment" and "Total outcome payments made" would ever be in different currencies.

_Current Data_

Currently "Total outcome payments made" has no data at all, so either option is possible.

**Comment by Juliana211** [comment]
Hello! We'll go for option B. Thanks!

**Comment by ghost** [comment]
Should "Maximum potential outcome payment"  have:

A) Amount, Amount USD, Currency?
B) currency, min amount, exact amount, max amount, min in USD, exact in USD, max in USD?

**Comment by Juliana211** [comment]
Hello! I think that we are fine with option A)

We use min and max amounts for the cases where social investors don't want to disclose exact amounts, but they usually don't have a problem with disclosing max potential outcome payment.

**Comment by ghost** [comment]
Now live
