### ISSUE TITLE
Investments ,Organisation  Role Category -> ENUM

### ISSUE THREAD

**Issue by ghost** [INDIGO-Initiative/indigo-data-standard#39]
Can you confirm what the full range of options should be?

- Nonprofit/NGO 
- Foundation/Philanthropist
- Government/Public Sector/Public Bank 
- Multilateral/Bilateral/Intergovernmental Financial Institution
- Corporate Giving 
- Investment Fund
- High Net Worth Individual/Family Office/Private Bank
- Impact Investor 
- Commercial

Are any missing?

[Note for @odscjames This needs fixed in project spreadsheet as some are truncated ]

**Comment by Juliana211** [comment]
Yes! This should be the list for investment orgs. Thanks.

**Comment by ghost** [comment]
Done
