### ISSUE TITLE
In data dictionary, show which tables allow multiple items and which are singular.

### ISSUE THREAD

**Issue by ghost** [INDIGO-Initiative/indigo-data-standard#41]
eg Fund, geographic_areas_for_outcome_payment

**Comment by ghost** [comment]
How about an entry in each section?

https://indigo-data-standard.readthedocs.io/en/indicate-lists/data-dictionary/fund.html#geographic-area-for-outcome-payment

If this is good, I will add to projects and organisations too

**Comment by Juliana211** [comment]
Yes, let's go for this option. Thanks!

**Comment by ghost** [comment]
Done
